name: "queensac-action"
description: "Check GitHub repository links and optionally open PRs to fix them."
author: "reddevilmidzy"
branding:
  icon: "link"
  color: "purple"
inputs:
  repo:
    description: "GitHub repository URL to scan (defaults to the workflow repository)."
    required: false
  branch:
    description: "Target branch to check and base branch for the pull request."
    required: false
  dry-run:
    description: "Skip pull request creation and only report results."
    default: "false"
    required: false
  github_app_id:
    description: "GitHub App ID to use when creating pull requests."
    required: false
  github_app_private_key:
    description: "GitHub App private key (PEM) to use when creating pull requests."
    required: false
runs:
  using: "composite"
  steps:
    - name: Install queensac
      shell: bash
      run: |
        set -eo pipefail
        rustup update stable
        cargo install --git https://github.com/reddevilmidzy/queensac --force --locked
        echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
    - name: Run queensac
      shell: bash
      env:
        QUEENSAC_APP_ID: ${{ inputs.github_app_id }}
        QUEENSAC_APP_PRIVATE_KEY: ${{ inputs.github_app_private_key }}
      run: |
        set -eo pipefail

        repo_input='${{ inputs.repo }}'
        if [ -z "${repo_input}" ]; then
          repo_input="https://github.com/${{ github.repository }}"
        fi

        cmd=(queensac --repo "${repo_input}")

        if [ -n "${{ inputs.branch }}" ]; then
          cmd+=("--branch" "${{ inputs.branch }}")
        fi

        if [ "${{ inputs.dry-run }}" = "true" ]; then
          cmd+=("--dry-run")
        fi
        "${cmd[@]}"
